name: Scrape Images

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  scrape-images:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - name: Install dependencies
        run: npm install
      - name: Find Chrome executable path
        run: which google-chrome-stable

      - name: Scrape images
        run: node scrape.js
      - name: Commit changes
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Scrape images"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
